import { randomUUID } from "node:crypto";
import path from "node:path";
import { mkdir, open, type FileHandle } from "node:fs/promises";
import {
  createBinarySanitizer,
  type BinarySanitizer,
  type BinarySanitizerOptions
} from "./binary";
import {
  parseRolloutRecord,
  parseRolloutRecordInput
} from "./schemas";
import {
  advanceStateHash,
  computeInitialStateHash
} from "./state";
import type {
  GenerationCompletedRecord,
  MessageCommittedRecord,
  ModelSessionInitializedRecord,
  RolloutCloseDetails,
  RolloutFinishedRecord,
  RolloutRecord,
  RolloutRecordCounts,
  RolloutRecordInput,
  RolloutStartedRecord,
  RolloutTerminalStatus,
  RolloutWriter
} from "./types";

const SAFE_FILE_SEGMENT = /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;
const RECENT_ID_WINDOW = 4_096;

export interface CreateRolloutWriterOptions
  extends Omit<BinarySanitizerOptions, "captureEnabled"> {
  rolloutId: string;
  activeLoopId: string;
  startedAt?: string | Date;
  binaryCaptureEnabled?: boolean;
  now?: () => Date;
}

export async function createRolloutWriter(
  options: CreateRolloutWriterOptions
): Promise<RolloutWriter> {
  assertIdentifier(options.rolloutId, "rolloutId");
  assertIdentifier(options.activeLoopId, "activeLoopId");
  const startedAt = normalizeTimestamp(options.startedAt ?? new Date());
  const directory = rolloutDayDirectory(options.tracesDir, startedAt);
  await mkdir(directory, { recursive: true });
  const fileName = rolloutFileName(startedAt, options.activeLoopId);
  const filePath = path.join(directory, fileName);
  const handle = await open(filePath, "ax", 0o600);
  const sanitizer = createBinarySanitizer({
    tracesDir: options.tracesDir,
    captureEnabled: options.binaryCaptureEnabled === true,
    ...(options.maxBlobBytes !== undefined
      ? { maxBlobBytes: options.maxBlobBytes }
      : {}),
    ...(options.defaultMediaType
      ? { defaultMediaType: options.defaultMediaType }
      : {})
  });
  return new FileRolloutWriter(
    handle,
    filePath,
    options.rolloutId,
    options.activeLoopId,
    sanitizer,
    options.now ?? (() => new Date())
  );
}

export function rolloutDayDirectory(
  tracesDir: string,
  timestamp: string | Date
): string {
  const date = new Date(timestamp);
  if (!Number.isFinite(date.getTime())) {
    throw new Error("Rollout timestamp is invalid.");
  }
  const [year, month, day] = date.toISOString().slice(0, 10).split("-");
  if (!year || !month || !day) {
    throw new Error("Rollout timestamp could not be converted to a date path.");
  }
  return path.join(tracesDir, year, month, day);
}

export function rolloutFileName(
  timestamp: string | Date,
  activeLoopId: string
): string {
  assertIdentifier(activeLoopId, "activeLoopId");
  const date = new Date(timestamp);
  if (!Number.isFinite(date.getTime())) {
    throw new Error("Rollout timestamp is invalid.");
  }
  const compactTimestamp = date
    .toISOString()
    .replace(/[-:]/g, "");
  return `rollout-${compactTimestamp}-${safeFileSegment(activeLoopId)}.jsonl`;
}

export function safeFileSegment(id: string): string {
  if (SAFE_FILE_SEGMENT.test(id)) {
    return id;
  }
  const encoded = Buffer.from(id, "utf8").toString("base64url");
  return `b64-${encoded}`;
}

class FileRolloutWriter implements RolloutWriter {
  private queue: Promise<void> = Promise.resolve();
  private closing = false;
  private started = false;
  private initialized = false;
  private currentStateHash: string | undefined;
  private currentMessageCount = 0;
  // UUIDs are generated by the runtime. A bounded recent window catches
  // accidental immediate reuse without retaining every id for a long-lived
  // rollout; the reader performs the authoritative full-file validation.
  private readonly recordIds = new RecentIdSet(RECENT_ID_WINDOW);
  private readonly messageIds = new RecentIdSet(RECENT_ID_WINDOW);
  private readonly generationIds = new RecentIdSet(RECENT_ID_WINDOW);
  private readonly outboundActionIds = new RecentIdSet(RECENT_ID_WINDOW);
  private readonly outboundActions = new Map<
    string,
    { toolName: string }
  >();
  private counts: RolloutRecordCounts = emptyCounts();

  constructor(
    private readonly handle: FileHandle,
    readonly filePath: string,
    readonly rolloutId: string,
    private readonly activeLoopId: string,
    private readonly sanitizer: BinarySanitizer,
    private readonly now: () => Date
  ) {}

  get stateHash(): string | undefined {
    return this.currentStateHash;
  }

  get messageCount(): number {
    return this.currentMessageCount;
  }

  append(record: RolloutRecordInput): Promise<void> {
    if (this.closing) {
      return Promise.reject(new Error("Rollout writer is already closing."));
    }
    return this.enqueue(async () => {
      const sanitized = await this.sanitizer.sanitize(record);
      const input = parseRolloutRecordInput(sanitized);
      const prepared = this.prepareRecord(input);
      await this.writeRecord(prepared);
    });
  }

  flush(options: { durable?: boolean } = {}): Promise<void> {
    if (this.closing) {
      return this.queue;
    }
    return this.enqueue(async () => {
      if (options.durable === true) {
        await this.handle.sync();
      }
    });
  }

  close(
    status: RolloutTerminalStatus,
    details: RolloutCloseDetails = {}
  ): Promise<void> {
    if (this.closing) {
      return this.queue;
    }
    this.closing = true;
    const closeOperation = this.queue
      .then(async () => {
        if (!this.started) {
          throw new Error("A rollout cannot close before rollout_started.");
        }
        const summary = {
          ...this.counts,
          recordCount: this.counts.recordCount + 1,
          unresolvedOutboundActionCount: this.outboundActions.size
        };
        const candidate = {
          id: randomUUID(),
          rolloutId: this.rolloutId,
          timestamp: this.now().toISOString(),
          type: "rollout_finished" as const,
          status,
          summary,
          ...(details.reason ? { reason: details.reason } : {}),
          ...(details.metadata !== undefined
            ? { metadata: details.metadata }
            : {})
        };
        const sanitized = await this.sanitizer.sanitize(candidate);
        const record = parseRolloutRecord(sanitized);
        if (record.type !== "rollout_finished") {
          throw new Error("Expected a rollout_finished record.");
        }
        this.assertCommonRecord(record);
        await this.writeRecord(record);
        await this.handle.sync();
      })
      .finally(async () => {
        await this.handle.close();
      });
    this.queue = closeOperation;
    return closeOperation;
  }

  private enqueue(operation: () => Promise<void>): Promise<void> {
    const result = this.queue.then(operation);
    this.queue = result;
    return result;
  }

  private prepareRecord(input: RolloutRecordInput): RolloutRecord {
    this.assertCommonRecord(input);
    if (!this.started && input.type !== "rollout_started") {
      throw new Error("rollout_started must be the first rollout record.");
    }

    let record: RolloutRecord;
    switch (input.type) {
      case "rollout_started":
        record = this.prepareStarted(input);
        break;
      case "model_session_initialized":
        record = this.prepareInitialized(input);
        break;
      case "message_committed":
        record = this.prepareCommitted(input);
        break;
      case "generation_completed":
        record = this.prepareGeneration(input);
        break;
      case "outbound_action_started": {
        if (this.outboundActionIds.has(input.actionId)) {
          throw new Error(`Outbound action ${input.actionId} was already started.`);
        }
        this.outboundActionIds.add(input.actionId);
        this.outboundActions.set(input.actionId, {
          toolName: input.toolName
        });
        record = input;
        break;
      }
      case "outbound_action_finished": {
        const startedAction = this.outboundActions.get(input.actionId);
        if (!startedAction) {
          throw new Error(
            `Outbound action ${input.actionId} finished without a durable start.`
          );
        }
        this.outboundActions.delete(input.actionId);
        record = input;
        break;
      }
      case "tool_completed":
      case "span_completed":
        record = input;
        break;
    }

    return parseRolloutRecord(record);
  }

  private prepareStarted(input: RolloutStartedRecord): RolloutStartedRecord {
    if (this.started) {
      throw new Error("A rollout may contain only one rollout_started record.");
    }
    if (input.activeLoopId !== this.activeLoopId) {
      throw new Error("rollout_started activeLoopId does not match the writer.");
    }
    this.started = true;
    return input;
  }

  private prepareInitialized(
    input: Omit<ModelSessionInitializedRecord, "stateHash"> & {
      stateHash?: string;
    }
  ): ModelSessionInitializedRecord {
    if (this.initialized) {
      throw new Error("A rollout may initialize its model session only once.");
    }
    assertUniqueMessageIds(input.messages, this.messageIds);
    const stateHash = computeInitialStateHash(input.messages, input.tools);
    if (input.stateHash && input.stateHash !== stateHash) {
      throw new Error("model_session_initialized stateHash is not canonical.");
    }
    this.initialized = true;
    this.currentStateHash = stateHash;
    this.currentMessageCount = input.messages.length;
    return { ...input, stateHash };
  }

  private prepareCommitted(
    input: Omit<MessageCommittedRecord, "previousStateHash" | "stateHash"> & {
      previousStateHash?: string;
      stateHash?: string;
    }
  ): MessageCommittedRecord {
    const previousStateHash = this.requireState();
    if (
      input.previousStateHash &&
      input.previousStateHash !== previousStateHash
    ) {
      throw new Error("message_committed previousStateHash is stale.");
    }
    if (this.messageIds.has(input.message.id)) {
      throw new Error(`Message ${input.message.id} is already committed.`);
    }
    const stateHash = advanceStateHash(previousStateHash, input.message);
    if (input.stateHash && input.stateHash !== stateHash) {
      throw new Error("message_committed stateHash is not canonical.");
    }
    this.messageIds.add(input.message.id);
    this.currentStateHash = stateHash;
    this.currentMessageCount += 1;
    return { ...input, previousStateHash, stateHash };
  }

  private prepareGeneration(
    input: Omit<
      GenerationCompletedRecord,
      "inputStateHash" | "inputMessageCount"
    > & {
      inputStateHash?: string;
      inputMessageCount?: number;
    }
  ): GenerationCompletedRecord {
    const inputStateHash = this.requireState();
    if (input.inputStateHash && input.inputStateHash !== inputStateHash) {
      throw new Error("generation_completed inputStateHash is stale.");
    }
    if (
      input.inputMessageCount !== undefined &&
      input.inputMessageCount !== this.currentMessageCount
    ) {
      throw new Error("generation_completed inputMessageCount is stale.");
    }
    if (this.generationIds.has(input.generationId)) {
      throw new Error(`Generation ${input.generationId} was already recorded.`);
    }
    if (input.status === "cancelled" && input.outputMessageIds.length > 0) {
      throw new Error("Cancelled generations cannot commit output message ids.");
    }
    this.generationIds.add(input.generationId);
    return {
      ...input,
      inputStateHash,
      inputMessageCount: this.currentMessageCount
    };
  }

  private assertCommonRecord(record: {
    id: string;
    rolloutId: string;
  }): void {
    if (record.rolloutId !== this.rolloutId) {
      throw new Error("Rollout record belongs to a different rollout.");
    }
    if (this.recordIds.has(record.id)) {
      throw new Error(`Rollout record id ${record.id} is duplicated.`);
    }
    this.recordIds.add(record.id);
  }

  private requireState(): string {
    if (!this.initialized || !this.currentStateHash) {
      throw new Error("The model session has not been initialized.");
    }
    return this.currentStateHash;
  }

  private async writeRecord(record: RolloutRecord): Promise<void> {
    await this.handle.appendFile(`${JSON.stringify(record)}\n`, "utf8");
    this.counts.recordCount += 1;
    switch (record.type) {
      case "model_session_initialized":
        this.counts.messageCount += record.messages.length;
        break;
      case "message_committed":
        this.counts.messageCount += 1;
        break;
      case "generation_completed":
        this.counts.generationCount += 1;
        break;
      case "tool_completed":
        this.counts.toolCount += 1;
        break;
      case "outbound_action_started":
        this.counts.outboundActionCount += 1;
        break;
      case "span_completed":
        this.counts.spanCount += 1;
        break;
      case "rollout_started":
      case "outbound_action_finished":
      case "rollout_finished":
        break;
    }
  }
}

function emptyCounts(): RolloutRecordCounts {
  return {
    recordCount: 0,
    messageCount: 0,
    generationCount: 0,
    toolCount: 0,
    outboundActionCount: 0,
    unresolvedOutboundActionCount: 0,
    spanCount: 0
  };
}

function assertUniqueMessageIds(
  messages: readonly { id: string }[],
  destination: Pick<RecentIdSet, "has" | "add">
): void {
  for (const message of messages) {
    if (destination.has(message.id)) {
      throw new Error(`Message ${message.id} is duplicated.`);
    }
    destination.add(message.id);
  }
}

class RecentIdSet {
  private readonly values = new Map<string, undefined>();

  constructor(private readonly limit: number) {}

  has(value: string): boolean {
    return this.values.has(value);
  }

  add(value: string): void {
    this.values.delete(value);
    this.values.set(value, undefined);
    if (this.values.size <= this.limit) {
      return;
    }
    const oldest = this.values.keys().next().value;
    if (oldest !== undefined) {
      this.values.delete(oldest);
    }
  }
}

function normalizeTimestamp(value: string | Date): string {
  const date = new Date(value);
  if (!Number.isFinite(date.getTime())) {
    throw new Error("Rollout timestamp is invalid.");
  }
  return date.toISOString();
}

function assertIdentifier(value: string, name: string): void {
  if (!value.trim()) {
    throw new Error(`${name} must be non-empty.`);
  }
}
