packages:
  - 'packages/*'
  - 'harness'
injectWorkspacePackages: true
allowBuilds:
  '@mongodb-js/zstd': false
  agent-browser: true
  esbuild: true
  node-liblzma: false
  onnxruntime-node: false
  protobufjs: false
  sharp: true
